package com.ado.moviesub.integrations.tests;

import com.ado.moviesub.app.entity.user.User;
import com.ado.moviesub.integrations.tests.util.TestData;
import org.junit.Ignore;
import org.junit.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class UserIntegrationTest extends BaseIntegrationTest {

  @Test
  public void testCreateUser(){
    User requestUser = TestData.createSampleUser("testCreateUser");

    ResponseEntity<User> httpResponse = createUser(requestUser);
    assertEquals(httpResponse.getStatusCode(), HttpStatus.OK);

    User responseUser = httpResponse.getBody();

    assertNotNull("Id of user must be generated by the server", responseUser.getId());
    assertEquals(requestUser.getAge(), responseUser.getAge());
    assertEquals(requestUser.getEmail(), responseUser.getEmail());
    assertEquals(requestUser.getUserName(), responseUser.getUserName());
  }

  @Ignore
  @Test
  public void testGetUser(){
    User sampleUser = TestData.createSampleUser("testGetUser");

    ResponseEntity<User> httpResponse = createUser(sampleUser);
    assertEquals(httpResponse.getStatusCode(), HttpStatus.OK);

    User createdUser = httpResponse.getBody();
    httpResponse = getUser(createdUser.getId());

    assertEquals(httpResponse.getStatusCode(), HttpStatus.OK);
    assertEquals(createdUser, httpResponse.getBody());
  }
}
